apiVersion: apps/v1
kind: Deployment
metadata:
  name: candyscan-daemon-ui
  labels:
    name: candyscan-daemon-ui
    app: CANdyScan
    app.kubernetes.io/part-of: CANdyScan
    role: daemon-ui
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: candyscan-daemon-ui
  template:
    metadata:
      labels:
        name: candyscan-daemon-ui
        app: CANdyScan
        app.kubernetes.io/part-of: CANdyScan
        role: daemon-ui
        env: prod
    spec:
      containers:
        - image: ghcr.io/patrik-stas/indyscan/indyscan-daemon-ui:4.6.1
          name: candyscan-daemon-ui
          ports:
            - containerPort: 3710
          env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"
            - name: PORT
              value: "3710"
            - name: PROXY_API_URL
              value: http://candyscan-daemon:3709
