apiVersion: v1
kind: Service
metadata:
  name: candyscan-daemon-ui
  labels:
    name: candyscan-daemon-ui
    app.kubernetes.io/part-of: CANdyScan
    env: prod
spec:
  selector:
    app: candyscan-daemon-ui
  ports:
    - protocol: TCP
      port: 3710
      targetPort: 3710
