apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: indyscan-elasticsearch
  name: indyscan-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: indyscan-elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/esnet: "true"
        io.kompose.service: indyscan-elasticsearch
    spec:
      containers:
        - env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
          name: indyscan-elasticsearch
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources: {}
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: indyscan-es
      restartPolicy: Always
      volumes:
        - name: indyscan-es
          persistentVolumeClaim:
            claimName: indyscan-es
status: {}
