apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: indyscan-kibana
  name: indyscan-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: indyscan-kibana
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/esnet: "true"
        io.kompose.service: indyscan-kibana
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: http://indyscan-elasticsearch.indyscan.svc.dev.idlab.org:9200
          image: docker.elastic.co/kibana/kibana:7.6.1
          name: indyscan-kibana
          ports:
            - containerPort: 5601
          resources: {}
      restartPolicy: Always
status: {}
