apiVersion: v1
kind: Service
metadata:
  name: candyscan-search-engine-ui
  labels:
    name: candyscan-search-engine-ui
    app: CANdyScan
    app.kubernetes.io/part-of: CANdyScan
    role: search-engine-ui
    env: prod
spec:
  selector:
    name: candyscan-search-engine-ui
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
