apiVersion: apps/v1
kind: Deployment
metadata:
  name: candyscan-daemon
  labels:
    name: candyscan-daemon
    app: CANdyScan
    app.kubernetes.io/part-of: CANdyScan
    role: daemon
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: candyscan-daemon
  template:
    metadata:
      labels:
        name: candyscan-daemon
        app: CANdyScan
        app.kubernetes.io/part-of: CANdyScan
        role: daemon
        env: prod
    spec:
      containers:
        - image: ghcr.io/patrik-stas/indyscan/indyscan-daemon:4.6.1
          name: candyscan-daemon
          env:
            - name: AUTOSTART
              value: "true"
            - name: ENABLE_LOGFILES
              value: "false"
            - name: LOG_HTTP_REQUESTS
              value: "true"
            - name: LOG_HTTP_RESPONSES
              value: "true"
            - name: LOG_LEVEL
              value: info
            - name: SERVER_ENABLED
              value: "true"
            - name: SERVER_PORT
              value: "3709"
            - name: WORKER_CONFIGS
              value: /home/indyscan/indyscan-daemon/app-configs/candydev.json
          volumeMounts:
            - mountPath: /home/indyscan/indyscan-daemon/app-configs/candydev.json
              name: candyscan-daemon-volume
              subPath: candydev.json
            - mountPath: /home/indyscan/indyscan-daemon/app-configs/genesis/CANDY_DEV.txn
              name: candyscan-daemon-volume
              subPath: candydev.txn
      volumes:
        - name: candyscan-daemon-volume
          configMap:
            name: candyscan-daemon
            items:
              - key: daemon_config.json
                path: candydev.json
              - key: candydev.txn
                path: candydev.txn
