apiVersion: apps/v1
kind: Deployment
metadata:
  name: candyscan-elasticsearch
  labels:
    name: candyscan-elasticsearch
    app: CANdyScan
    app.kubernetes.io/part-of: CANdyScan
    role: search-engine
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CANdyScan
  template:
    metadata:
      labels:
        name: candyscan-elasticsearch
        app: CANdyScan
        app.kubernetes.io/part-of: CANdyScan
        role: search-engine
        env: prod
    spec:
      containers:
        - name: candyscan-elasticsearch
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: candyscan-elasticsearch
      volumes:
        - name: candyscan-elasticsearch
          persistentVolumeClaim:
            claimName: candyscan-elasticsearch
