apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: candyscan-elasticsearch
  labels:
    name: candyscan-elasticsearch
    io.kompose.service: candyscan-elasticsearch
    app.kubernetes.io/part-of: CANdyScan
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
