apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: candyscan-search-engine
  labels:
    name: candyscan-search-engine
    app: CANdyScan
    io.kompose.service: candyscan-search-engine
    app.kubernetes.io/part-of: CANdyScan
    role: search-engine
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
