apiVersion: apps/v1
kind: Deployment
metadata:
  name: candyscan-daemon
  labels:
    name: candyscan-daemon
    app: CANdyScan
    app.kubernetes.io/part-of: CANdyScan
    role: daemon
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: candyscan-daemon
  template:
    metadata:
      labels:
        name: candyscan-daemon
        app: CANdyScan
        app.kubernetes.io/part-of: CANdyScan
        role: daemon
        env: prod
    spec:
      containers:

        - name: candyscan-daemon
          # image: ghcr.io/patrik-stas/indyscan/indyscan-daemon:4.6.1
          image: image-registry.openshift-image-registry.svc:5000/ca7f8f-tools/indyscan-daemon-ocp:4.6.1
          env:
            - name: AUTOSTART
              value: "true"
            - name: ENABLE_LOGFILES
              value: "false"
            - name: LOG_HTTP_REQUESTS
              value: "true"
            - name: LOG_HTTP_RESPONSES
              value: "true"
            - name: LOG_LEVEL
              value: info
            - name: SERVER_ENABLED
              value: "true"
            - name: SERVER_PORT
              value: "3709"
            - name: WORKER_CONFIGS
              value: /home/indyscan/indyscan-daemon/app-configs/candydev.json,/home/indyscan/indyscan-daemon/app-configs/candytest.json,/home/indyscan/indyscan-daemon/app-configs/candyprod.json

          volumeMounts:
            - mountPath: /home/indyscan/indyscan-daemon/app-configs/candydev.json
              name: candyscan-daemon-volume
              subPath: candydev.json
            - mountPath: /home/indyscan/indyscan-daemon/app-configs/candytest.json
              name: candyscan-daemon-volume
              subPath: candytest.json
            - mountPath: /home/indyscan/indyscan-daemon/app-configs/candyprod.json
              name: candyscan-daemon-volume
              subPath: candyprod.json

            - mountPath: /home/indyscan/indyscan-daemon/app-configs/genesis/CANDY_DEV.txn
              name: candyscan-daemon-volume
              subPath: candydev.txn
            - mountPath: /home/indyscan/indyscan-daemon/app-configs/genesis/CANDY_TEST.txn
              name: candyscan-daemon-volume
              subPath: candytest.txn
            - mountPath: /home/indyscan/indyscan-daemon/app-configs/genesis/CANDY_PROD.txn
              name: candyscan-daemon-volume
              subPath: candyprod.txn

      volumes:
        - name: candyscan-daemon-volume
          configMap:
            name: candyscan-daemon
            items:
              - key: candydev.json
                path: candydev.json
              - key: candytest.json
                path: candytest.json
              - key: candyprod.json
                path: candyprod.json

              - key: candydev.txn
                path: candydev.txn
              - key: candytest.txn
                path: candytest.txn
              - key: candyprod.txn
                path: candyprod.txn
