apiVersion: apps/v1
kind: Deployment
metadata:
  name: candyscan-web
  labels:
    name: candyscan-web
    app: CANdyScan
    app.kubernetes.io/part-of: CANdyScan
    role: web
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: candyscan-web
  template:
    metadata:
      labels:
        name: candyscan-web
        app: CANdyScan
        app.kubernetes.io/part-of: CANdyScan
        role: web
        env: prod
    spec:
      containers:
        - name: candyscan-web
          image: ghcr.io/patrik-stas/indyscan/indyscan-webapp:4.6.1
          ports:
            - containerPort: 3707
          env:
            - name: DAEMON_WS_URL
              value: http://candyscan-daemon:3709
            - name: INDYSCAN_API_URL
              value: http://candyscan-api:3708
            - name: LOG_HTTP_REQUESTS
              value: "true"
            - name: LOG_HTTP_RESPONSES
              value: "true"
            - name: LOG_LEVEL
              value: debug
            - name: PORT
              value: "3707"
