apiVersion: v1
kind: ConfigMap
metadata:
  name: candyscan-api
  labels:
    name: candyscan-api
    app.kubernetes.io/part-of: CANdyScan
    role: api
    env: prod
data:
  api_config.json: |
    [
      {
        "id": "CANDY_DEV",
        "ui": {
          "priority": 1,
          "display": "CANdy-dev",
          "display-long": "CANdy-dev Indy Network",
          "description": "Development network for collaboration between Quebec, Ontario and British-Columbia.",
          "tutorial": "This Indy Explorer is hosted in Canada by IDLab",
          "tutorial-link": "https://idlab.org/",
          "logo-address": ""
        },
        "aliases": [
          "CANDY_DEV"
        ],
        "es" : {
          "index": "txs-candydev"
        }
      }
    ]
